### ISSUE TITLE
Lack of installation instructions

### ISSUE THREAD

**Issue by VladimirShitov** [epurdom/GloScope#2]
Hi, and thank you for your tool and paper! Could you also add the installation instructions? There is only a line of code, which imports the package the [vignette](https://github.com/epurdom/GloScope/blob/main/vignettes/GlosTutorial.Rmd) but no advice on how to install it. Also, I would move this vignette to a readme file in the root of the repository.

Thanks again!

**Comment by wtorous** [comment]
Dear Vladimir,

Thank you for your interest in our package and helpful suggestions. We have added a README which explains how `devtools::install_github` can currently be used to install the package. We expect the package to be added to BioConductor within the next week as well. We have also added a link to the vignettes folder in the README and a copy of the knit HTML output.

Sincerely,
William

**Comment by VladimirShitov** [comment]
Thank you, this is perfect! Looking forward to using your package.
