### ISSUE TITLE
Negative values, when calculating JS-divergence with KNN density estimation

### ISSUE THREAD

**Issue by VladimirShitov** [epurdom/GloScope#3]
Hi, and thanks again for your package! Looking forward to a new Bioconductor release with it.

I ran gloscope on the [COMBAT](https://pubmed.ncbi.nlm.nih.gov/35216673/) dataset with parameters `dens = "KNN"` and `dist_mat="JS"`. Surprisingly, quite a few values in the resulting matrix turned out to be negative. Here is the histogram of a flattened matrix:

![image](https://github.com/epurdom/GloScope/assets/35199218/97279544-4366-4d06-ad09-a8ef335b734b)

The interpretation is unclear, and I wonder if this is an expected behavior.

**Comment by wtorous** [comment]
I agree with your interpretation that negative divergences arise when the within sample nearest neighbor distances are generally larger than the across sample distances. Using a zero divergence seems reasonable to me here, with the caveat to not interpret this as the distributions being exactly equal.
